verbose: false

instrumentation:
  root: .
  default-excludes: true
  # embed-source: true # seems that this option doesn't work!
    # https://github.com/istanbuljs/sample-mocha-compilers/issues/3
  # complete-copy: true
  # include-all-sources: true
  # variable: __coverage__
  # compact: false
  # preserve-comments: true
  # complete-copy: true
  # save-baseline: false
  # baseline-file: ./coverage/coverage-baseline.json

reporting:
  print: summary
  reports:
    - lcov
  dir: ./coverage/server
  # watermarks:
  #   statements: [50, 80]
  #   lines: [50, 80]
  #   functions: [50, 80]
  #   branches: [50, 80]

# hooks:
#   hook-run-in-context: false
